# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
repos:
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.1.3.9137
    hooks:
    -   id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style]
    -   id: use-tidy-description
    -   id: deps-in-desc
    -   id: parsable-R
    -   id: no-browser-statement
    -   id: readme-rmd-rendered
    -   id: roxygenize
        additional_dependencies:
        -    dplyr
        -    glue
        -    knitr
        -    lubridate
        -    magrittr
        -    memoise
        -    openxlsx
        -    purrr
        -    readr
        -    rlang
        -    rmarkdown
        -    scales
        -    stringr
        -    testit
        -    testthat
        -    tibble
        -    tidyr
        -    tidyselect
        -    usethis
        -    xmart4
        -    zoo
        -    gpw13/whoville
        -    gpw13/xmart4
        -    WorldHealthOrganization/wppdistro
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=200']
    -   id: end-of-file-fixer
        exclude: '\.Rd'
-   repo: local
    hooks:
    -   id: forbid-to-commit
        name: Don't commit common R artifacts
        entry: Cannot commit .Rhistory, .RData, .Rds or .rds.
        language: fail
        files: '\.Rhistory|\.RData|\.Rds|\.rds$'
